<<<<<<< HEAD
<<<<<<< HEAD
name: CI

on:
  push:
    branches:
    - dev

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@dev
    - uses: actions/setup-node@dev
      with:
        node-version: '10.x'
    - run: yarn
    - run: yarn build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
||||||| cac4212
=======
name: deploy_to_firebase_hosting

on:
  push:
    branches:
      - dev

jobs:
  deploy_to_firebase_hosting:

    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout the repository
        uses: actions/checkout@master
      - run : yarn && yarn build      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
>>>>>>> 996eac5853cd32655c992925f321bf06216a9116
||||||| merged common ancestors
=======
name: deploy_to_firebase_hosting
on:
  push:
    branches:
      - dev

jobs:
  deploy_to_firebase_hosting:

    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout the repository
        uses: actions/checkout@master
      - run : yarn && yarn build      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
>>>>>>> 4fc881ae8720fdbda4b78932c4df25ed6da6e959
